<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class GeneratedReport extends Model
{
    use HasFactory;

    protected $fillable = [
        'report_type',
        'report_title',
        'academic_year',
        'time_period',
        'time_period_description',
        'filename',
        'file_path',
        'total_records',
        'summary_data',
        'generated_by',
        'generated_by_role',
        'generated_at',
        'file_size',
        'status',
        'error_message',
    ];

    protected $casts = [
        'summary_data' => 'array',
        'generated_at' => 'datetime',
        'total_records' => 'integer',
    ];

    /**
     * Scope to get reports by type
     */
    public function scopeByType($query, $type)
    {
        return $query->where('report_type', $type);
    }

    /**
     * Scope to get reports by academic year
     */
    public function scopeByAcademicYear($query, $year)
    {
        return $query->where('academic_year', $year);
    }

    /**
     * Scope to get reports by time period
     */
    public function scopeByTimePeriod($query, $period)
    {
        return $query->where('time_period', $period);
    }

    /**
     * Scope to get completed reports only
     */
    public function scopeCompleted($query)
    {
        return $query->where('status', 'completed');
    }

    /**
     * Scope to get reports generated by specific user
     */
    public function scopeByUser($query, $user)
    {
        return $query->where('generated_by', $user);
    }

    /**
     * Scope to get recent reports
     */
    public function scopeRecent($query, $days = 30)
    {
        return $query->where('generated_at', '>=', Carbon::now()->subDays($days));
    }

    /**
     * Get formatted file size
     */
    public function getFormattedFileSizeAttribute()
    {
        if (!$this->file_size) {
            return 'Unknown';
        }

        $bytes = (int) $this->file_size;
        $units = ['B', 'KB', 'MB', 'GB'];
        
        for ($i = 0; $bytes > 1024 && $i < count($units) - 1; $i++) {
            $bytes /= 1024;
        }
        
        return round($bytes, 2) . ' ' . $units[$i];
    }

    /**
     * Get human readable report type
     */
    public function getHumanReadableTypeAttribute()
    {
        $types = [
            'good_moral_applicants' => 'Good Moral Applicants',
            'residency_applicants' => 'Residency Applicants',
            'minor_violators' => 'Minor Violators',
            'major_violators' => 'Major Violators',
            'overall_report' => 'Overall Violations Report',
            'minor_offenses_overall' => 'Minor Offenses Overall Report',
        ];

        return $types[$this->report_type] ?? ucfirst(str_replace('_', ' ', $this->report_type));
    }

    /**
     * Get human readable time period
     */
    public function getHumanReadableTimePeriodAttribute()
    {
        if ($this->time_period_description) {
            return $this->time_period_description;
        }

        $periods = [
            'all' => 'All Time',
            'daily' => 'Daily',
            'monthly' => 'Monthly',
            'yearly' => 'Yearly',
            'first_semester' => 'First Semester',
            'second_semester' => 'Second Semester',
            'summer_term' => 'Summer Term',
        ];

        // Handle monthly_X format
        if (strpos($this->time_period, 'monthly_') === 0) {
            $month = (int) str_replace('monthly_', '', $this->time_period);
            $monthNames = [
                1 => 'January', 2 => 'February', 3 => 'March', 4 => 'April',
                5 => 'May', 6 => 'June', 7 => 'July', 8 => 'August',
                9 => 'September', 10 => 'October', 11 => 'November', 12 => 'December'
            ];
            return $monthNames[$month] ?? 'Monthly';
        }

        return $periods[$this->time_period] ?? ucfirst(str_replace('_', ' ', $this->time_period));
    }

    /**
     * Create a new report record
     */
    public static function createReportRecord($data)
    {
        return self::create([
            'report_type' => $data['report_type'],
            'report_title' => $data['report_title'],
            'academic_year' => $data['academic_year'],
            'time_period' => $data['time_period'],
            'time_period_description' => $data['time_period_description'] ?? null,
            'filename' => $data['filename'],
            'file_path' => $data['file_path'] ?? null,
            'total_records' => $data['total_records'] ?? 0,
            'summary_data' => $data['summary_data'] ?? null,
            'generated_by' => $data['generated_by'],
            'generated_by_role' => $data['generated_by_role'],
            'generated_at' => $data['generated_at'] ?? now(),
            'file_size' => $data['file_size'] ?? null,
            'status' => $data['status'] ?? 'completed',
            'error_message' => $data['error_message'] ?? null,
        ]);
    }

    /**
     * Get report statistics
     */
    public static function getStatistics()
    {
        return [
            'total_reports' => self::count(),
            'completed_reports' => self::completed()->count(),
            'failed_reports' => self::where('status', 'failed')->count(),
            'reports_this_month' => self::whereMonth('generated_at', Carbon::now()->month)
                                        ->whereYear('generated_at', Carbon::now()->year)
                                        ->count(),
            'most_generated_type' => self::selectRaw('report_type, COUNT(*) as count')
                                        ->groupBy('report_type')
                                        ->orderByDesc('count')
                                        ->first(),
        ];
    }

    /**
     * Get reports by date range
     */
    public static function getByDateRange($startDate, $endDate)
    {
        return self::whereBetween('generated_at', [$startDate, $endDate])
                   ->orderByDesc('generated_at')
                   ->get();
    }
}
